### ISSUE TITLE
Bugfix: Pfeil soll nicht mit Spieler kollidieren

### ISSUE THREAD

**Issue by Rahza** [PSMGGamesSS2015/PSMG_SS_2015_Shootergame#10]
Pfeil kollidiert aktuell mit Spieler, führt zu seltsamem Verhalten. Abändern, so dass der Pfeil zwar noch mit allem anderen kollidiert, aber nicht mit dem Spieler

**Comment by maischter** [comment]
Pfeil wird aufgesammelt

**Comment by mark-engerisser** [comment]
Hat sich erledigt, da Pfeilaufsammelfeature nun vorhanden.
