### ISSUE TITLE
Pfeil GameObject zerstören

### ISSUE THREAD

**Issue by Rahza** [PSMGGamesSS2015/PSMG_SS_2015_Shootergame#12]
GameObject des Pfeils muss zerstört werden, damit nicht zu viele Objekte in der Szene entstehen. Bedingungen: zu klären (nach gewisser Zeit?)

**Comment by LenaManschewski** [comment]
man könnte nach einer bestimmten anzahl an pfeilen die ersten zerstören. Also ich meine wenn man 5 pfeile geschossen hat und den 6. schießt verschwindet der erste usw.
oder
man machts echt nach zeit. also das man zb nach ner minute die objekte zerstört.. da könnte man halt sowas wie wieder aufsammeln implementieren wenn sie nich kaputt gegangen sind dabei.

**Comment by maischter** [comment]
Ich wär für eine begrenzte Anzahl an Pfeilen. Verballerte Pfeile können wieder aufgesammelt werden. Damit begrenzt sich die Zahl der Pfeile und man kann auch nicht einfach Munition spammen.
