### ISSUE TITLE
Alles mal in eine Scene packen

### ISSUE THREAD

**Issue by maischter** [PSMGGamesSS2015/PSMG_SS_2015_Shootergame#129]
Sämtliche Funktionalitäten etc. die benötigt werden in eine Scene (philippsSpielwiese). Janina Bitte das Terrain rüberkopieren. Mark bitte den Rest

**Comment by mark-engerisser** [comment]
das meißte ist wieder in der mainscene. Bis auf Terrain. OB das UI auf dem neuesten Stand ist weiß ich auch nicht
