### ISSUE TITLE
Gegner greifen Spieler an

### ISSUE THREAD

**Issue by Rahza** [PSMGGamesSS2015/PSMG_SS_2015_Shootergame#150]
Wenn in Sichtfeld, sollen Gegner den Spieler angreifen. Mit Bogen wäre zwar cool aber sicher zu aufwändig, vielleicht zumindest Faustattacken

**Comment by mark-engerisser** [comment]
Bei mir geht immernoch gar nichts was mit gegnern zu tun hat. Morgen mal Zeit mich da aufzuklären?
